name    'ssh_hardening'
version '0.1.0'
source 'https://github.com/TelekomLabs/puppet-ssh-hardening'
author 'Dominik Richter'
license 'Apache License, Version 2.0'
summary 'Installs and configures OpenSSH with hardening'
description 'Installs and configures OpenSSH with hardening'
project_page 'https://github.com/TelekomLabs/puppet-ssh-hardening'
