name    'hardening/ssh_hardening'
version '1.0.5'
source 'https://github.com/TelekomLabs/puppet-ssh-hardening'
author 'Dominik Richter'
license 'Apache License, Version 2.0'
summary 'Installs and configures OpenSSH with hardening'
description 'Installs and configures OpenSSH with hardening'
project_page 'https://github.com/TelekomLabs/puppet-ssh-hardening'

dependency 'saz/ssh', '>= 2.3.6'
dependency 'puppetlabs/stdlib', '>= 4.2.0'
